name: build

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Try to build Docker image
      run: docker build --build-arg CACHE_DATE=$(date +%Y-%m-%d:%H:%M:%S) -t my/eksplein .
